# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

sudo: required

os:
    - linux

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_CHECK_ARGS="--no-vignettes --no-manual --no-examples"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true" 

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq netcdf-bin libnetcdf-dev

r_github_packages:
  - yihui/printr

branches:
  except:
  - procUsgs

notifications:
  email:
    on_success: change
    on_failure: change